AllCops:
  Exclude:
      - vendor/**/*
      - Gemfile*
      - '*.gemspec'
  NewCops: enable
  TargetRubyVersion: 2.6

Layout/LineLength:
  Max: 150

Style/FrozenStringLiteralComment:
  Enabled: false

Style/MutableConstant:
  Enabled: false
