  require:
    - rubocop-md
    - rubocop-performance
    - rubocop-rake
    - rubocop-rspec
    # - rubocop-jekyll

  AllCops:
    Exclude:
      - demo/_site/**/*
      - binstub/**/*
      - vendor/**/*
      - Gemfile*
    NewCops: enable

  Gemspec/DeprecatedAttributeAssignment:
    Enabled: false

Gemspec/RequiredRubyVersion:
  Enabled: false

  Gemspec/RequireMFA:
    Enabled: false

  Layout/HashAlignment:
    EnforcedColonStyle: table
    EnforcedHashRocketStyle: table

  Layout/LineLength:
    Max: 150

  Layout/CommentIndentation:
    Exclude:
      - spec/**/*

  Layout/MultilineMethodCallIndentation:
    Enabled: false

  Lint/RedundantCopDisableDirective:
    Exclude:
      - jekyll_time_since.gemspec

  Metrics/AbcSize:
    Max: 30

  Metrics/BlockLength:
    Exclude:
      - jekyll_time_since.gemspec

  Metrics/CyclomaticComplexity:
    Max: 20

  Metrics/MethodLength:
    Max: 40

  RSpec/ExampleLength:
    Max: 20

  RSpec/MultipleExpectations:
    Max: 15

  Style/Documentation:
    Enabled: false

  Style/FrozenStringLiteralComment:
    Enabled: false

  Style/TrailingCommaInHashLiteral:
    EnforcedStyleForMultiline: comma
