author: Mike Slinn
domain: bogus.jekylldemo.com
email: bogus@jekylldemo.com
exclude:  # Wildcards are not supported yet https://github.com/jekyll/jekyll-watch/pull/93
  - .git
  - .github
  - .gitignore
  - .jekyll-cache
  - .jekyll-metadata
  - .ruby-version
  - .vscode
  - BingSiteAuth.xml
  - Gemfile
  - Gemfile.lock
  - README.md
ignore_theme_config: true
liquid:
  error_mode: strict
  # strict_filters: true
  # strict_variables: true
plugin_loggers:
  PluginMetaLogger: info
permalink: "/blog/:year/:month/:day/:title:output_ext"
plugin-vars:
  github: 'https://github.com'
  django-github: 'https://github.com/django/django/blob/3.1.7'
  django-oscar-github: 'https://github.com/django-oscar/django-oscar/blob/3.0.2'
plugins: # Use file name of the plugin entry point, not the gem name
  - jekyll
  - jekyll_plugin_logger
  - jekyll_time_since
  - classifier-reborn
  - html-proofer
sass:
  style: compressed
title: <span class='code'>Jekyll_time_since</span> Plugin
url: https://bogus.jekylldemo.com
