source 'https://rubygems.org'

gem 'jekyll'

group :jekyll_plugins do
  gem 'classifier-reborn'
  gem 'html-proofer'
  gem 'jekyll-environment-variables'
  gem 'jekyll-tagging'
  gem 'jekyll_time_since', path: '../'
end

gem 'debase', '0.2.5.beta2', require: false
gem 'ruby-debug-ide', require: false
