source 'https://rubygems.org'

gem 'jekyll'
# gem 'nokogumbo'
# gem 'ptools'
# gem 'sprockets'
# gem 'webrick'

group :jekyll_plugins do
  gem 'classifier-reborn'
  gem 'html-proofer'
  # gem 'jekyll-assets'
  gem 'jekyll-environment-variables'
  gem 'jekyll_time_since', path: '../'
  gem 'jekyll-tagging'
end

gem "bundler", require: false
gem 'debase', "0.2.5.beta2", require: false
# gem 'debase-ruby_core_source', '0.10.18', require: false
gem "liquid", require: false
# gem "rake", "~> 13.0", require: false
gem 'reek', require: false
# gem 'reline', '0.3.1', require: false
gem "rubocop", "~> 1.44.0", require: false
# gem 'rubocop-jekyll'
gem 'rubocop-rake', require: false
gem 'rubocop-rspec', require: false
gem 'ruby-debug-ide', require: false
